language: vim
dist: focal
before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/junegunn/fzf.git
  git clone https://github.com/junegunn/fzf.vim.git
script: |
  vim -Nu <(cat << VIMRC
  set rtp+=vader.vim
  set rtp+=fzf
  set rtp+=fzf.vim
  set rtp+=.
  VIMRC) -c 'Vader! test/*' > /dev/null
